// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATR33Iu1IfH4eCJ5dZV8zvV2Ayt7_CyDo',
    appId: '1:264796317155:web:c1b06c1107bdc58c5f6cd6',
    messagingSenderId: '264796317155',
    projectId: 'geomugger-18a74',
    authDomain: 'geomugger-18a74.firebaseapp.com',
    storageBucket: 'geomugger-18a74.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANTUP6rX2UHXN7qfU0YPOd0JDkovrTAow',
    appId: '1:264796317155:android:7cfb9bc3baf06cec5f6cd6',
    messagingSenderId: '264796317155',
    projectId: 'geomugger-18a74',
    storageBucket: 'geomugger-18a74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjlJJWnJeRum0yY-EBFrnihXxNguXD_74',
    appId: '1:264796317155:ios:e2353dd4c34189c65f6cd6',
    messagingSenderId: '264796317155',
    projectId: 'geomugger-18a74',
    storageBucket: 'geomugger-18a74.firebasestorage.app',
    iosBundleId: 'com.example.geoMugger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjlJJWnJeRum0yY-EBFrnihXxNguXD_74',
    appId: '1:264796317155:ios:e2353dd4c34189c65f6cd6',
    messagingSenderId: '264796317155',
    projectId: 'geomugger-18a74',
    storageBucket: 'geomugger-18a74.firebasestorage.app',
    iosBundleId: 'com.example.geoMugger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATR33Iu1IfH4eCJ5dZV8zvV2Ayt7_CyDo',
    appId: '1:264796317155:web:96799dbb6fb3abaf5f6cd6',
    messagingSenderId: '264796317155',
    projectId: 'geomugger-18a74',
    authDomain: 'geomugger-18a74.firebaseapp.com',
    storageBucket: 'geomugger-18a74.firebasestorage.app',
  );

}