import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:geo_mugger/widgets/Authentication/auth_gate.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'firebase_options.dart'; // Generated by flutterfire configure


void main() async {
  // 1. Initialize native engine interaction layer
  WidgetsFlutterBinding.ensureInitialized();
  
  String? initError;

  try {
    // 2. Attempt to parse your geomugger-18a74 configuration keys
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    ).timeout(const Duration(seconds: 6)); // Safety timeout prevents infinite stalling
  } catch (e, stacktrace) {
    // 3. Catch any configuration exceptions or handshaking dropouts
    initError = e.toString();
    debugPrint("=== CRITICAL FIREBASE CONFIG ERROR ===");
    debugPrint(e.toString());
    debugPrint(stacktrace.toString());
  }
  
  await dotenv.load(fileName: ".env");
  // 4. Fire up the application framework loop
  runApp(MyApp(errorString: initError));
}

class MyApp extends StatelessWidget {
  final String? errorString;
  const MyApp({super.key, this.errorString});
  
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'GeoMugger',
      theme: ThemeData(primarySwatch: Colors.blue,), // <- added this
      debugShowCheckedModeBanner: false,
      // If an initialization error happened, show it immediately. Otherwise, mount the Gate.
      home: errorString != null 
          ? FirebaseCrashFallback(errorMessage: errorString!) 
          : const AuthGate(),
    );
  }
}



/// Fallback screen that breaks the infinite loading loop if Firebase fails
class FirebaseCrashFallback extends StatelessWidget {
  final String errorMessage;
  const FirebaseCrashFallback({super.key, required this.errorMessage});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.red[900],
      body: Padding(
        padding: const EdgeInsets.all(24.0),
        child: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              const Icon(Icons.gpp_bad, color: Colors.white, size: 64),
              const SizedBox(height: 16),
              const Text(
                "Firebase Initialization Failed",
                style: TextStyle(color: Colors.white, fontSize: 24, fontWeight: FontWeight.bold),
              ),
              const SizedBox(height: 16),
              Container(
                padding: const EdgeInsets.all(16),
                decoration: BoxDecoration(color: Colors.white12, borderRadius: BorderRadius.circular(8)),
                child: SingleChildScrollView(
                  child: Text(
                    errorMessage,
                    style: const TextStyle(color: Colors.white70, fontFamily: 'monospace', fontSize: 14),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

// to prepopulate firebase with the default tags
Future<void> prePopulateTags() async {
  DocumentReference tagRef = FirebaseFirestore.instance
                            .collection('metadata')
                            .doc('tags_list');
  Map<String, List<String>> tagData  = {
    'Vibes': ['Bright', 'Cozy', 'Chill', 'Dark Academia', 'Library', 'Quiet', 'White noise'],
    'Amenities': ['Air con', 'Comfortable seats', 'Discussion Area', 'Lamp', 'Multiple seats', 'Power Outlet', 'Printer', 'Standing desk' 'Wifi'],
    'Facilities near-by': ['Bus stop', 'Bookshop', 'Car park', 'Convenience store', 'Food Court', 'Garden', 'Public toilet', 'Mall', 'MRT']
  };

  try {
    await tagRef.set(tagData, SetOptions(merge: true));
    print("tag data successfully populated");
  } catch(error) {
    print("error incurred from prepopulating: $error");
  }
}
