name: Deploy App
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x ./deploy.sh

      - name: Deploy
        run: ./deploy.sh